/**
 * Represents the failure of a parsing operation.
 */
export type ParseFailure = {
  success: false;
  expected?: string;
};

/**
 * Represents the success of a parsing operation.
 */
export type ParseSuccess<O> = {
  success: true;
  value: O;
  rem: string;
};

/**
 * The result of a parsing operation.
 */
export type ParseResult<O> = ParseSuccess<O> | ParseFailure;

/**
 * A parser.
 */
export type Parser<O> = (input: string) => ParseResult<O>;

/**
 * Creates a parser that does not consume any input and always returns a value.
 */
export const success = <O>(value: O): Parser<O> => (input) => {
  return {
    success: true,
    value,
    rem: input,
  };
};

/**
 * Creates a parser that consumes a target string and returns it.
 */
export const str = (target: string): Parser<string> => (input) => {
  if (input.startsWith(target)) {
    return {
      success: true,
      value: target,
      rem: input.slice(target.length),
    };
  }
  return {
    success: false,
    expected: target,
  };
};

/**
 * Creates a parser that returns the next char in the input if it satisfies a
 * predicate.
 */
export const sat =
  (pred: (char: string) => boolean): Parser<string> => (input) => {
    const char = input[0];
    if (char !== undefined && pred(char)) {
      return {
        success: true,
        value: char,
        rem: input.slice(1),
      };
    }
    return { success: false };
  };

/**
 * Creates a parser that negates the result of another parser. Does not consume
 * any input.
 */
export const not = <O>(parser: Parser<O>): Parser<void> => (input) => {
  const res = parser(input);
  if (res.success) {
    return { success: false };
  }
  return {
    success: true,
    value: undefined,
    rem: input,
  };
};

/**
 * A parser that returns the next char in the input.
 */
export const any: Parser<string> = sat(() => true);

/**
 * A parser that succeeds if there is no more input.
 */
export const eof: Parser<void> = not(any);

/**
 * Creates a parser that calls two parsers in sequence and returns the pair of
 * results.
 */
export const seq =
  <O1, O2>(p1: Parser<O1>, p2: Parser<O2>): Parser<[O1, O2]> => (input) => {
    const res1 = p1(input);
    if (!res1.success) {
      return res1;
    }
    const res2 = p2(res1.rem);
    if (!res2.success) {
      return res2;
    }
    return {
      success: true,
      value: [res1.value, res2.value],
      rem: res2.rem,
    };
  };

/**
 * Creates a parser that tries to call the first parser, and if it fails, calls
 * the second parser.
 */
export const alt = <O>(p1: Parser<O>, p2: Parser<O>): Parser<O> => (input) => {
  const res = p1(input);
  return res.success ? res : p2(input);
};

/**
 * Creates a parser that maps the result of a parser using a function.
 */
export const map =
  <O1, O2>(parser: Parser<O1>, f: (value: O1) => O2): Parser<O2> => (input) => {
    const res = parser(input);
    if (!res.success) {
      return res;
    }
    return {
      success: true,
      value: f(res.value),
      rem: res.rem,
    };
  };

/**
 * Creates a parser that accumulates successful calls to the given parser until
 * it returns a failure.
 */
export const many0 = <O>(parser: Parser<O>): Parser<O[]> => (input) => {
  const arr = [];
  let rem = input;
  while (true) {
    const res = parser(rem);
    if (!res.success) {
      break;
    }
    rem = res.rem;
    arr.push(res.value);
  }
  return {
    success: true,
    value: arr,
    rem,
  };
};

/**
 * Same as `many0` but expects at least one successful call to the given parser.
 */
export const many1 = <O>(parser: Parser<O>): Parser<O[]> =>
  map(seq(parser, many0(parser)), ([first, rest]) => [first, ...rest]);

/**
 * Creates a parser that lazily calls a parser generated by a function.
 */
export const lazy = <O>(f: () => Parser<O>): Parser<O> => (input) => f()(input);

/**
 * Creates a parser that calls two parsers in sequence and returns the left
 * result.
 */
export const left = <O1, O2>(l: Parser<O1>, r: Parser<O2>): Parser<O1> =>
  map(seq(l, r), ([v1]) => v1);

/**
 * Creates a parser that calls two parsers in sequence and returns the right
 * result.
 */
export const right = <O1, O2>(l: Parser<O1>, r: Parser<O2>): Parser<O2> =>
  map(seq(l, r), ([, v2]) => v2);

/**
 * Creates a parser that calls three parsers in sequence and returns the second
 * result.
 */
export const between = <O1, O2, O3>(
  l: Parser<O1>,
  parser: Parser<O2>,
  r: Parser<O3>,
): Parser<O2> => right(l, left(parser, r));

/**
 * Creates a parser that parses alternating sequences of elements and
 * separators. A trailing separator is excluded. Empty sequences are allowed.
 */
export const sep = <O1, O2>(
  parser: Parser<O1>,
  sep: Parser<O2>,
): Parser<O1[]> =>
  alt(
    map(
      seq(parser, many0(map(seq(sep, parser), ([, v]) => v))),
      ([first, rest]) => [first, ...rest],
    ),
    success([]),
  );
